name: Build Engines for React native

on:
  workflow_call:
    inputs:
      commit:
        description: 'Commit on the given branch to build'
        type: string
        required: false

jobs:
  build-ios:
    name: 'iOS build for commit ${{ inputs.commit }}'
    runs-on: macos-14

    steps:
      - name: Output link to real commit
        run: echo ${{ github.repository }}/commit/${{ inputs.commit }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: prisma/prisma-engines
          ref: ${{ inputs.commit }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-ios,aarch64-apple-ios,aarch64-apple-ios-sim

      - run: |
          cd query-engine/query-engine-c-abi
          make ios
      - uses: actions/upload-artifact@v4
        with:
          name: ios
          path: |
            ${{ github.workspace }}/query-engine/query-engine-c-abi/ios/*

  build-android:
    name: 'Android build for commit ${{ inputs.commit }}'
    runs-on: ubuntu-latest

    steps:
      - name: Output link to real commit
        run: echo ${{ github.repository }}/commit/${{ inputs.commit }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: prisma/prisma-engines
          ref: ${{ inputs.commit }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - run: |
          cd query-engine/query-engine-c-abi
          make android

      - uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            ${{ github.workspace }}/query-engine/query-engine-c-abi/android/*

  combine-artifacts:
    # Do not change `name`, prisma-engines Buildkite build job depends on this name ending with the commit
    name: 'Combine iOS and Android artifacts on branch ${{ github.event.ref }} for commit ${{ inputs.commit }}'
    runs-on: ubuntu-latest
    needs:
      - build-ios
      - build-android
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-native
          path: |
            ${{ github.workspace }}/ios
            ${{ github.workspace }}/android
