name: Build Engines for Windows

on:
  workflow_call:
    inputs:
      commit:
        description: 'Commit on the given branch to build'
        type: string
        required: false

jobs:
  build:
    name: 'Windows engines build for commit ${{ inputs.commit }}'
    env:
      SQLITE_MAX_VARIABLE_NUMBER: 250000
      SQLITE_MAX_EXPR_DEPTH: 10000
      RUSTFLAGS: '-C target-feature=+crt-static'
    runs-on: windows-latest

    steps:
      - name: Output link to real commit
        run: echo ${{ github.repository }}/commit/${{ inputs.commit }}

      - name: Checkout ${{ inputs.commit }}
        uses: actions/checkout@v4
        with:
          repository: prisma/prisma-engines
          ref: ${{ inputs.commit }}

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            ${{ github.workspace }}/target/release/*.exe
            ${{ github.workspace }}/target/release/*.dll
